kind: pipeline
name: default

steps:
  - name: build
    image: node
    commands:
      - yarn
      - yarn build

  - name: build & delpoy
    image: docker/compose:1.24.1
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker-compose up -d --build


volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
