version: '3'
services:
  production:
    image: registry.cchampou.me/blog:latest
    build: .
    restart: always
    deploy:
      replicas: 5
    labels:
      - "traefik.frontend.rule=Host:blog.cchampou.me"
      - "traefik.backend.port=3000"
      - "traefik.enable=true"

networks:
  default:
    external:
      name: layko_layko_net
