version: '3'
services:
  production:
    image: registry.cchampou.me/blog:latest
    build: .
    restart: always
    labels:
      - "traefik.frontend.rule=Host:test.cchampou.me"
      - "traefik.backend.port=3000"
      - "traefik.enable=true"
      - "traefik.docker.network=layko_layko_net"

networks:
  default:
    external:
      name: layko_layko_net
